# Generated by Django 2.1.2 on 2019-01-16 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fastrunner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=1024)),
            ],
            options={
                'verbose_name': '全局变量',
                'db_table': 'Variables',
            },
        ),
        migrations.RenameField(
            model_name='report',
            old_name='body',
            new_name='summary',
        ),
        migrations.RemoveField(
            model_name='report',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='report',
            name='failure',
        ),
        migrations.RemoveField(
            model_name='report',
            name='skipped',
        ),
        migrations.RemoveField(
            model_name='report',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='report',
            name='success',
        ),
        migrations.RemoveField(
            model_name='report',
            name='total',
        ),
        migrations.AddField(
            model_name='report',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fastrunner.Project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='type',
            field=models.IntegerField(choices=[(1, '调试用例报告'), (2, '异步任务报告'), (3, '定时任务报告')], default=1, verbose_name='报告类型'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='api',
            name='name',
            field=models.CharField(max_length=100, verbose_name='接口名称'),
        ),
        migrations.AlterField(
            model_name='api',
            name='url',
            field=models.CharField(max_length=200, verbose_name='请求地址'),
        ),
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(max_length=100, verbose_name='用例名称'),
        ),
        migrations.AlterField(
            model_name='casestep',
            name='name',
            field=models.CharField(max_length=100, verbose_name='用例名称'),
        ),
        migrations.AlterField(
            model_name='casestep',
            name='url',
            field=models.CharField(max_length=200, verbose_name='请求地址'),
        ),
        migrations.AlterField(
            model_name='config',
            name='name',
            field=models.CharField(max_length=100, verbose_name='环境名称'),
        ),
        migrations.AlterField(
            model_name='database',
            name='name',
            field=models.CharField(max_length=100, verbose_name='数据库名称'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='项目名称'),
        ),
        migrations.AddField(
            model_name='variables',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fastrunner.Project'),
        ),
    ]
